# -*- coding: utf-8 -*-
"""dense net.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pkm7vCOnyeKLFWxoH2o5vgEt_Nu3b46l
"""

import sys, os
from os import listdir
from os.path import isfile, join

from tensorflow import keras
# from tensorflow.keras import layers

from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
from keras.layers import Conv2D, MaxPooling2D, Embedding, LSTM, concatenate
from keras.layers import Activation, Dropout, Flatten, Dense
from keras import backend as K

from keras.applications import DenseNet201
from keras.applications.densenet import preprocess_input

from scipy import misc
import numpy as np
import cv2 as cv

import matplotlib.pyplot as plt
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')
path = '/content/drive/MyDrive/CNNdata2'

labelledClassesNames = [ dI for dI in listdir( f'{path}/training_small_full' ) ]
labelledClasses = {}

for className in labelledClassesNames:

    trainingPath = f'{path}/training_small_full/' + className
    validationPath = f'{path}/validation_small/' + className

    labelledClasses[className] = {}
    labelledClasses[className]['training'] = len( [ f for f in listdir( trainingPath ) if isfile( join ( trainingPath, f ) ) ] )
    labelledClasses[className]['validation'] = len( [ f for f in listdir( validationPath ) if isfile( join ( validationPath, f ) ) ] )


img_height, img_width = 369, 496

training_directory = path + '/training_small_full'
validation_directory = path + '/validation_small'

if K.image_data_format() == 'channels_first':
    input_shape = (3, img_width, img_height)
else:
    input_shape = (img_width, img_height, 3)

epochs = 10
batch_size = 20

train_dataset = keras.utils.image_dataset_from_directory(
    training_directory,
    image_size = (img_width, img_height),
    label_mode = 'categorical',
    batch_size=batch_size
)

validation_dataset = keras.utils.image_dataset_from_directory(
    validation_directory,
    image_size = (img_width, img_height),
    label_mode = 'categorical',
    batch_size=batch_size
)

for images, labels in train_dataset:
    preprocess_input(images)

for images, labels in validation_dataset:
    preprocess_input(images)

from tensorflow.keras.models import Model
from keras.layers.normalization.batch_normalization_v1 import BatchNormalization
from keras.layers import GlobalAveragePooling2D
from keras import regularizers

model = DenseNet201(weights='imagenet',include_top=False, input_shape = input_shape)
for layer in model.layers[0:]:
  layer.trainable=False

#for layer in model.layers[-8:]:
  #layer.trainable=True

x = model.output
x = BatchNormalization()(x)
x = GlobalAveragePooling2D()(x)
x = BatchNormalization()(x)
x = Dense(64,activation='relu', kernel_regularizer=regularizers.l2())(x)
x = Dropout(0.6)(x)
preds = Dense(7,activation='softmax')(x)

model=Model(inputs= model.input,outputs=preds)

def step_decay(epoch):
   initial_lrate = 0.02
   drop = 0.5
   epochs_drop = 1.0
   lrate = initial_lrate * math.pow(drop, math.floor((1+epoch)/epochs_drop))
   return lrate
lrate = LearningRateScheduler(step_decay)

model.compile(optimizer=keras.optimizers.Adam(),loss='categorical_crossentropy',metrics=['accuracy'])

keras.utils.plot_model(model, show_shapes=True)

model.summary()

filepath="/content/drive/MyDrive/dense_net_final/model-epoch-{epoch:02d}-val_accuracy-{val_accuracy:.2f}.hdf5"

checkpoint = ModelCheckpoint(
    filepath,
    monitor='val_accuracy',
    verbose=1,
    save_best_only=True,
    mode='max')

model.fit(
    train_dataset,
    steps_per_epoch= 1960 // batch_size,
    epochs=epochs,
    validation_data=validation_dataset,
    validation_steps= 210 // batch_size,
    callbacks= checkpoint,
    verbose=1
)

test_directory = path + '/test_small'

test_dataset = keras.utils.image_dataset_from_directory(
    test_directory,
    image_size = (img_width, img_height),
    label_mode = 'categorical',
    batch_size=batch_size
)

saved_model = keras.models.load_model(filepath='/content/drive/MyDrive/dense_net_final/model-epoch-01-val_accuracy-0.25.hdf5')

cnf_matrix = [['label','art rock', 'garage rock', 'grunge', 'hard rock', 'heavy metal', 'punk rock', 'soft rock'],
              ['art rock',0,0,0,0,0,0,0],
              ['garage rock', 0,0,0,0,0,0,0],
              ['grunge',0,0,0,0,0,0,0],
              ['hard rock',0,0,0,0,0,0,0],
              ['heavy metal', 0,0,0,0,0,0,0],
              ['punk rock', 0,0,0,0,0,0,0],
              ['soft rock',0,0,0,0,0,0,0]]
cnf_df = pd.DataFrame(cnf_matrix[1:], columns=cnf_matrix[0])

for className in labelledClassesNames:
  unseenPath = '/content/drive/MyDrive/CNNdata2/test_small/' + className
  for f in os.listdir( unseenPath ):
    if os.path.isfile( os.path.join ( unseenPath, f ) ) and f != ".DS_Store":
      filePath = unseenPath + "/" + f
      spectrogramFile = keras.preprocessing.image.load_img(filePath, target_size=(496,369))
      spectrogramFile = np.reshape(spectrogramFile, [1, 496, 369 ,3])
      prediction = saved_model.predict( spectrogramFile )
      probability_array = saved_model.predict( spectrogramFile )
      pred = np.argmax(probability_array, axis=-1)

      #predicted = row, actual = column
      cnf_df.at[pred[0], className] += 1

cnf_df