# -*- coding: utf-8 -*-
"""other models.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PT_lUY1O5AugvxCJKfQAg55rhRL14Kj_
"""

import sys, os
import pandas as pd
import numpy as np

from sklearn import linear_model
from sklearn.preprocessing import MinMaxScaler
from sklearn import metrics
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

train_data = pd.read_csv(r"/content/drive/MyDrive/train_features.csv")
validation_data = pd.read_csv(r"/content/drive/MyDrive/validation_features.csv")

dataset = pd.concat([train_data, validation_data])
dataset.head()
dataset.tail()

y_train = dataset['label']
x_train = dataset.drop(columns=['label',"filename"],axis=1)

print(x_train.shape, y_train.shape)

test_data = pd.read_csv(r"/content/drive/MyDrive/test_features.csv")
y_test = test_data['label']
x_test = test_data.drop(columns=["label","filename"], axis=1)

object= MinMaxScaler()

x_train = object.fit_transform(x_train)
x_test = object.fit_transform(x_test)

"""LOGISTIC REGRESSION!"""

model = linear_model.LogisticRegression(max_iter=10000, multi_class="multinomial")
model.fit(x_train, y_train)
y_pred = model.predict(x_test)

from sklearn.metrics import roc_auc_score
from sklearn.metrics import f1_score



print("Accuracy score: " + str(metrics.accuracy_score(y_test, y_pred)))

y_pred_probs = model.predict_proba(x_test)
print("ROC AUC score: " + str(roc_auc_score(y_test, y_pred_probs, multi_class="ovr")))

print("f1 score: " + str(f1_score(y_test, y_pred, average="weighted")))

print(y_pred_probs)

"""KNN!!!"""

KNNmodel = KNeighborsClassifier(n_neighbors=30, metric="euclidean")
KNNmodel.fit(x_train, y_train)
y_pred = KNNmodel.predict(x_test)

KNN_matrix = metrics.confusion_matrix(y_test, y_pred, labels=['art rock','garage rock','grunge','hard rock','heavy metal','punk rock','soft rock'])
print(KNN_matrix)

print("Accuracy score: " + str(metrics.accuracy_score(y_test, y_pred)))

y_pred_probs = KNNmodel.predict_proba(x_test)
print("ROC AUC score: " + str(roc_auc_score(y_test, y_pred_probs, multi_class="ovr")))

print("f1 score: " + str(f1_score(y_test, y_pred, average="weighted")))

"""Decision tree CLASSIFIER"""

from sklearn import tree

DTmodel = tree.DecisionTreeClassifier()
DTmodel.fit(x_train, y_train)
y_pred = DTmodel.predict(x_test)

DT_matrix = metrics.confusion_matrix(y_test, y_pred, labels=['art rock','garage rock','grunge','hard rock','heavy metal','punk rock','soft rock'])
print(DT_matrix)

print("Accuracy score: " + str(metrics.accuracy_score(y_test, y_pred)))

y_pred_probs = DTmodel.predict_proba(x_test)
print("ROC AUC score: " + str(roc_auc_score(y_test, y_pred_probs, multi_class="ovr")))

print("f1 score: " + str(f1_score(y_test, y_pred, average="weighted")))

from sklearn import naive_bayes

GNBmodel = naive_bayes.MultinomialNB()
GNBmodel.fit(x_train, y_train)
y_pred = GNBmodel.predict(x_test)

GNB_matrix = metrics.confusion_matrix(y_test, y_pred, labels=['art rock','garage rock','grunge','hard rock','heavy metal','punk rock','soft rock'])
print(GNB_matrix)

print("Accuracy score: " + str(metrics.accuracy_score(y_test, y_pred)))

y_pred_probs = GNBmodel.predict_proba(x_test)
print("ROC AUC score: " + str(roc_auc_score(y_test, y_pred_probs, multi_class="ovr")))

print("f1 score: " + str(f1_score(y_test, y_pred, average="weighted")))

SVMmodel = svm.SVC(probability=True,decision_function_shape='ovr', kernel="poly", degree=3)
SVMmodel.fit(x_train, y_train)
y_pred = SVMmodel.predict(x_test)

SVM_matrix = metrics.confusion_matrix(y_test, y_pred, labels=['art rock','garage rock','grunge','hard rock','heavy metal','punk rock','soft rock'])
print(SVM_matrix)

print("Accuracy score: " + str(metrics.accuracy_score(y_test, y_pred)))

y_pred_probs = SVMmodel.predict_proba(x_test)
print("ROC AUC score: " + str(roc_auc_score(y_test, y_pred_probs, multi_class="ovr")))

print("f1 score: " + str(f1_score(y_test, y_pred, average="weighted")))

y_train_for_xgb = y_train.replace(to_replace = ['art rock','garage rock','grunge','hard rock','heavy metal','punk rock','soft rock'],
                                  value = [0, 1, 2, 3, 4, 5, 6], inplace = False)
y_test_for_xgb = y_test.replace(to_replace = ['art rock','garage rock','grunge','hard rock','heavy metal','punk rock','soft rock'],
                                  value = [0, 1, 2, 3, 4, 5, 6], inplace = False)

import xgboost as xgb

xgbmodel = xgb.XGBClassifier()
xgbmodel.fit(x_train, y_train_for_xgb)

y_pred = xgbmodel.predict(x_test)

xgb_matrix = metrics.confusion_matrix(y_test_for_xgb, y_pred, labels=[0, 1, 2, 3, 4, 5, 6])
print(xgb_matrix)

print("Accuracy score: " + str(metrics.accuracy_score(y_test_for_xgb, y_pred)))

y_pred_probs = xgbmodel.predict_proba(x_test)
print("ROC AUC score: " + str(roc_auc_score(y_test_for_xgb, y_pred_probs, multi_class="ovr")))

print("f1 score: " + str(f1_score(y_test_for_xgb, y_pred, average="weighted")))