# -*- coding: utf-8 -*-
"""sequential_CNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LWh8s6BGzgLTjHa4vkkhoReRa9ig4-Ej
"""

import sys, os
from os import listdir
from os.path import isfile, join

from tensorflow import keras
# from tensorflow.keras import layers

# from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.callbacks import ModelCheckpoint, EarlyStopping
from keras.layers import Conv2D, MaxPooling2D, Embedding, LSTM, concatenate, BatchNormalization
from keras.layers import Activation, Dropout, Flatten, Dense
from keras import backend as K

from scipy import misc
import numpy as np
import cv2 as cv

import matplotlib.pyplot as plt
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')
path = '/content/drive/MyDrive/CNNdata2'

listdir(path)

"""Prepare the Data"""

labelledClassesNames = [ dI for dI in listdir( f'{path}/training_small_full' ) ]
labelledClasses = {}

for className in labelledClassesNames:

    trainingPath = f'{path}/training_small_full/' + className
    validationPath = f'{path}/validation_small/' + className

    labelledClasses[className] = {}
    labelledClasses[className]['training'] = len( [ f for f in listdir( trainingPath ) if isfile( join ( trainingPath, f ) ) ] )
    labelledClasses[className]['validation'] = len( [ f for f in listdir( validationPath ) if isfile( join ( validationPath, f ) ) ] )

labelledClasses

img = cv.imread(path + '/training_small_full/garage rock/Welcome To Japan [IZg4rz3cIDc]1.png')
img= cv.cvtColor(img, cv.COLOR_BGR2RGB)  # convert from BGR to RGB
print(img.shape)
plt.axis('off')
plt.imshow(img)

img_height, img_width = 369, 496

training_directory = path + '/training_small_full'
validation_directory = path + '/validation_small'

epochs = 10
batch_size = 28

if K.image_data_format() == 'channels_first':
    input_shape = (3, img_width, img_height)
else:
    input_shape = (img_width, img_height, 3)

model = keras.Sequential()

#
model.add(Conv2D(input_shape=input_shape, filters=32, kernel_size=(3,3), activation="relu"))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(filters=32,kernel_size=(3,3), activation="relu"))
model.add(MaxPooling2D(pool_size=(2,2)))


model.add(Conv2D(filters=64, kernel_size=(3,3), activation="relu"))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(filters=64, kernel_size=(3,3), activation="relu"))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(filters=64,kernel_size=(3,3), activation="relu"))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Conv2D(filters=128, kernel_size=(3,3), activation="relu"))
model.add(MaxPooling2D(pool_size=(2,2)))


#
model.add(Flatten())
model.add(Dense(128))
model.add(Activation('relu'))

# Classifying the data
model.add(Dropout(0.5))
model.add(Dense( len( labelledClasses)))
model.add(Activation('sigmoid'))

model.compile(optimizer=keras.optimizers.Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

model3 = keras.Sequential()
model3.add(Conv2D(input_shape=(496, 369, 3), filters=128, kernel_size=(3,3), activation="relu"))
model3.add(MaxPooling2D(pool_size=(2,2)))

model3.add(Flatten())
model3.add(Dense(7))
model3.add(Activation('sigmoid'))

model3.compile(optimizer=keras.optimizers.Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

keras.utils.plot_model(model3, show_shapes=True)

model.summary()

train_dataset = keras.utils.image_dataset_from_directory(
    training_directory,
    image_size = (img_width, img_height),
    label_mode = 'categorical',
    batch_size=batch_size
)

validation_dataset = keras.utils.image_dataset_from_directory(
    validation_directory,
    image_size = (img_width, img_height),
    label_mode = 'categorical',
    batch_size=batch_size
)

filepath="/content/drive/MyDrive/cnn_demo5/model-epoch-{epoch:02d}-val_accuracy-{val_accuracy:.2f}.hdf5"

checkpoint = ModelCheckpoint(
    filepath,
    monitor='val_accuracy',
    verbose=1,
    save_best_only=True,
    mode='max')

model.fit(
    train_dataset,
    steps_per_epoch= 1960 // batch_size,
    epochs=epochs,
    validation_data=validation_dataset,
    validation_steps= 210 // batch_size,
    callbacks= checkpoint,
    verbose=1
)

test_directory = path + '/test_small'

test_dataset = keras.utils.image_dataset_from_directory(
    test_directory,
    image_size = (img_width, img_height),
    label_mode = 'categorical',
    batch_size=batch_size
)

saved_model = keras.models.load_model(filepath='/content/drive/MyDrive/cnn_demo4/model-epoch-04-val_accuracy-0.32.hdf5')

saved_model.summary()

cnf_matrix = [['label','art rock', 'garage rock', 'grunge', 'hard rock', 'heavy metal', 'punk rock', 'soft rock'],
              ['art rock',0,0,0,0,0,0,0],
              ['garage rock', 0,0,0,0,0,0,0],
              ['grunge',0,0,0,0,0,0,0],
              ['hard rock',0,0,0,0,0,0,0],
              ['heavy metal', 0,0,0,0,0,0,0],
              ['punk rock', 0,0,0,0,0,0,0],
              ['soft rock',0,0,0,0,0,0,0]]

#what am i doing
cnf_df = pd.DataFrame(cnf_matrix[1:], columns=cnf_matrix[0])
cnf_df

labelledClassesNames

sortedClassesNames = sorted(labelledClassesNames)
sortedClassesNames

filePath = '/content/drive/MyDrive/CNNdata2/test_small/art rock/Big Log (2006 Remaster) [yS6tHqeHExU]1.png'
spectrogramFile = keras.preprocessing.image.load_img(filePath, target_size=(496,369))
spectrogramFile = np.reshape(spectrogramFile, [1, 496, 369,3])
probability_array = saved_model.predict( spectrogramFile )
pred = np.argmax(probability_array, axis=-1)
print(pred)

for className in labelledClassesNames:
  unseenPath = '/content/drive/MyDrive/CNNdata2/test_small/' + className
  for f in os.listdir( unseenPath ):
    if os.path.isfile( os.path.join ( unseenPath, f ) ) and f != ".DS_Store":
      filePath = unseenPath + "/" + f
      spectrogramFile = keras.preprocessing.image.load_img(filePath, target_size=(496,369))
      spectrogramFile = np.reshape(spectrogramFile, [1, 496, 369 ,3])
      prediction = saved_model.predict( spectrogramFile )
      probability_array = saved_model.predict( spectrogramFile )
      pred = np.argmax(probability_array, axis=-1)

      #predicted = row, actual = column
      cnf_df.at[pred[0], className] += 1

cnf_df